# !-----------------------------------------------------------------------------------------------!
#                         Welcome to AutoFarm Configuration - FarmSettings
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&c${project.name}&8]&7 "

databaseSettings:
  url: "jdbc:mysql://localhost:3306/farm_db"
  username: "root"
  password: ""

# -------------------------------------------------------------------------------------------------
# General Minion settings.
# Here you can customize the behavior of the minions during the farm phase.
# You can adjust the distance the minion will travel to collect resources and whether it can collect blocks vertically or horizontally.
# {distance} maximum distance he can break blocks
# {allow_vertical} enable/disable whether it can collect/place blocks vertically
# -------------------------------------------------------------------------------------------------
FarmSettings:
  distance: 2
  allow_vertical: false
  # - true -> vertical / horizontal
  # - false -> horizontal only

# -------------------------------------------------------------------------------------------------
# The formats used in the {timestamp}. For help with timestamp, see:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "dd.MM.yyyy HH:mm:ss"

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied 
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# NB: Don't forget to keep this up-to-date with the getConfigVersion method in your Settings class. 
# -------------------------------------------------------------------------------------------------
Version: 1