# !-----------------------------------------------------------------------------------------------!
#                         Welcome to AutoFarm Configuration - FarmSettings
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages.
# -------------------------------------------------------------------------------------------------
Prefix: '&8[&c${project.name}&8]&7 '

databaseSettings:
  url: 'jdbc:mysql://localhost:3306/farm_db'
  username: 'root'
  password: ''

# -------------------------------------------------------------------------------------------------
# General Minion settings.
# Here you can customize the behavior of the minions during the farm phase.
# You can adjust the distance the minion will travel to collect resources and whether it can collect blocks vertically or horizontally.
# {distance} maximum distance he can break blocks
# {allow_vertical} enable/disable whether it can collect/place blocks vertically
# -------------------------------------------------------------------------------------------------
FarmSettings:
  STONE:
    name: '<#ed9e00>Farm <bold><#009999>STONE</#009999></bold>'
    head-skin: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTUwM2MwMDg5MDMyNjYwNTA2N2ZmMTZmZmZiYzJkMDUwMjI1MWIzNjgwYzFhY2MxZDY4Y2QzZDA2NGQwNTc3In19fQ=='
    hand-item-nbt: '{Unbreakable:1,Enchantments:[{id:channeling,lvl:1},{id:vanishing_curse,lvl:1},{id:efficiency,lvl:7},{id:fire_aspect,lvl:4},{id:fire_protection,lvl:5},{id:flame,lvl:1},{id:unbreaking,lvl:7}]}'
    armor-nbt: '{Trim:{pattern:coast,material:lapis},display:{color:4673362}}'
    distance: 2
    allow_vertical: false
  WHEAT:
    name: '#ed9e00Farm #009999WHEAT</#009999>'
    head-skin: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjMyNTQ1YTk4OTdjNGYwODA5ZDdlOWQ3ZGU0YjQ5OWNhZmQ4ZDZhNDJhMGVhY2Y0Y2FhYmYzNDg4YWRjYTIxMSJ9fX0='
    hand-item-nbt: '{Unbreakable:1,Enchantments:[{id:channeling,lvl:1},{id:vanishing_curse,lvl:1},{id:efficiency,lvl:7},{id:fire_aspect,lvl:4},{id:fire_protection,lvl:5},{id:flame,lvl:1},{id:unbreaking,lvl:7}]}'
    armor-nbt: '{Trim:{pattern:coast,material:lapis},display:{color:4673362}}'
    distance: 2
    allow_vertical: false
  # - true -> vertical / horizontal
  # - false -> horizontal only

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# NB: Don't forget to keep this up-to-date with the getConfigVersion method in your Settings class.
# -------------------------------------------------------------------------------------------------
Version: 1
